### PR TITLE
Preserve the tag of the pulled image's name

### LINKED ISSUE #403: Image status is requested with the wrong image name
When launching a k8s pod with the docker hub `sameo/nginx-kubecon` image:

```
kubectl run nginx --image=sameo/nginx-kubecon:1.0 --port=80
```
(Note we're asking for a tagged image, not a `latest` one)

 `ocid` initially pulls and stores the image as expected:

```
# ocic image status -id 4a97d18023383cecad7694a2daf8383e093ccbdd36a1f1af862db90ed8b9f340
ID: 4a97d18023383cecad7694a2daf8383e093ccbdd36a1f1af862db90ed8b9f340
Tag: docker.io/sameo/nginx-kubecon:latest
Tag: sameo/nginx-kubecon:1.0
Tag: docker.io/sameo/nginx-kubecon
Size: 180932784
```

When launching a subsequent pod with the same image, `ocid` pulls the image again. After adding some debug in `vendor/github.com/containers/storage/storage/images.go` for dumping the images map (byname and byid), I see that the problem is `ocid` is asking for a status for an image with the name being set to `docker.io/sameo/nginx-kubecon:1.0` while we stored this image with the following tags:

```
Tag: docker.io/sameo/nginx-kubecon:latest
Tag: sameo/nginx-kubecon:1.0
Tag: docker.io/sameo/nginx-kubecon
```

As a consequence, the image is pulled again.

### PR DESCRIPTION
**Pull request by nalind**
When we pull an image, preserve the tag portion of the name that we were asked to use for pulling it, instead of unconditionally replacing it with "latest".  This aims to fix #403.

### CODE REVIEW

File: pkg/storage/image.go [hunk 1]
```diff
@@ -132,6 +133,9 @@ func (svc *imageService) PullImage(systemContext *types.SystemContext, imageName
 	dest := imageName
 	if srcRef.DockerReference() != nil {
 		dest = srcRef.DockerReference().Name()
+		if tagged, ok := srcRef.DockerReference().(reference.NamedTagged); ok {
```
Comment (runcom) [inline pkg/storage/image.go]: Do we have the same issue for digested images?

Comment (nalind) [inline pkg/storage/image.go]: Probably.

**Comment by sameo** [comment]
LGTM

**Comment by sameo** [comment]
Tested on an actual k8s deployment on top of ocid, works as expected.

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
Thanks for the quick fix @nalind :)

**Comment by runcom** [comment]
Let's follow up on my comment and get this fix in now :)

**Comment by runcom** [comment]
LGTM
