### PR TITLE
Make RemovePodSandbox idempotent

### LINKED ISSUE #240: RemovePodSandbox fails when being called multiple times
According to the CRI API spec/interface:

```
	// RemovePodSandbox removes the sandbox. If there are any running containers
	// in the sandbox, they must be forcibly terminated and removed.
	// This call is idempotent, and must not return an error if the sandbox has
	// already been removed.
```

However when trying to remove the same pod multiple times with ocic, we get the following error:

```
$ ocic pod create --config test/testdata/sandbox_config.json 
37174d9a500a0561f24f52077a485e3af48694bd7960223f89ceb118dc7c3614
$ ocic pod remove --id 37174d9a500a0561f24f52077a485e3af48694bd7960223f89ceb118dc7c3614
37174d9a500a0561f24f52077a485e3af48694bd7960223f89ceb118dc7c3614
$ ocic pod remove --id 37174d9a500a0561f24f52077a485e3af48694bd7960223f89ceb118dc7c3614
FATA[0000] removing the pod sandbox failed: rpc error: code = 2 desc = specified sandbox not found: 37174d9a500a0561f24f52077a485e3af48694bd7960223f89ceb118dc7c3614 
```

### PR DESCRIPTION
**Pull request by sameo**
And in particular make it not fail when removing an already removed
sandbox pod. According to the CRI spec:

  [RemovePodSandbox] is idempotent, and must not return an error if
  the sandbox has already been removed.

We now only print a warning instead of returning an error.

Fixes #240

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

File: server/sandbox_remove.go [hunk 1]
```diff
@@ -18,7 +18,9 @@ func (s *Server) RemovePodSandbox(ctx context.Context, req *pb.RemovePodSandboxR
 	logrus.Debugf("RemovePodSandboxRequest %+v", req)
 	sb, err := s.getPodSandboxFromRequest(req)
 	if err != nil {
-		return nil, err
```
Comment (runcom) [inline server/sandbox_remove.go]: This seems wrong as `getPodSandboxFromRequest` can return a legit error when the `req` doesn't contain a sandbox id at all. We should differentiate between "no sandbox id in req" (where we fail) and "can't find sandbox because it has been already removed" (where we pass).

Comment (runcom) [inline server/sandbox_remove.go]: Try with the following to see what I mean:
```sh
$ ocic pod remove --id ""
```

Comment (sameo) [inline server/sandbox_remove.go]: @runcom Should be fixed now.

File: server/sandbox_remove.go [hunk 2]
```diff
@@ -18,7 +18,13 @@ func (s *Server) RemovePodSandbox(ctx context.Context, req *pb.RemovePodSandboxR
...
+		if err == errSandboxIDEmpty {
+			return nil, err
+		}
+
+		resp := &pb.RemovePodSandboxResponse{}
+		logrus.Warnf("could not get sandbox: %v", err)
```
Comment (feiskyer) [inline server/sandbox_remove.go]: nit: make log more clear, e.g. `Couldn't get sandbox with ID %q, assuming it has already been removed`

File: server/sandbox.go [hunk 3]
```diff
@@ -60,7 +65,7 @@ type podSandboxRequest interface {
 func (s *Server) getPodSandboxFromRequest(req podSandboxRequest) (*sandbox, error) {
 	sbID := req.GetPodSandboxId()
 	if sbID == "" {
-		return nil, fmt.Errorf("PodSandboxId should not be empty")
+		return nil, errSandboxIDEmpty
```
Comment (xlgao-zju) [inline server/sandbox.go]: What's different between this and `fmt.Errorf`? Just curious.

Comment (sameo) [inline server/sandbox.go]: @xlgao-zju We return a named error so that we can check for a specific error in sandbox_remove.go:

```go
sb, err := s.getPodSandboxFromRequest(req)
if err != nil {
	if err == errSandboxIDEmpty {
		return nil, err
	}
```

**Comment by runcom** [comment]
LGTM, ping @mrunalp

**Comment by feiskyer** [comment]
LGTM
