### PR TITLE
Fix restore

### LINKED ISSUE #497: restore failures
rebooted a vm with origin + cri-o and I'm now seeing:
```
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                            -------------   --------        ------          -------
  43m           43m             1       kubelet, 192.168.122.186                        Warning         FailedSync      Error syncing pod, skipping: failed to "CreatePodSandbox" for "awesomeredis-1-bjr6t_default(774fcd7a-319c-11e7-8092-52540073f55c)" with CreatePodSandboxError: "CreatePodSandbox for pod \"awesomeredis-1-bjr6t_default(774fcd7a-319c-11e7-8092-52540073f55c)\" failed: rpc error: code = 2 desc = pod sandbox with name \"default-awesomeredis-1-bjr6t-0\" already exists"

  43m   43m     1       kubelet, 192.168.122.186                Warning FailedSync      Error syncing pod, skipping: failed to "CreatePodSandbox" for "awesomeredis-1-bjr6t_default(774fcd7a-319c-11e7-8092-52540073f55c)" with CreatePodSandboxError: "CreatePodSandbox for pod \"awesomeredis-1-bjr6t_default(774fcd7a-319c-11e7-8092-52540073f55c)\" failed: rpc error: code = 2 desc = conflict, name \"default-awesomeredis-1-bjr6t-0-infra\" already reserved for ctr \"62519a382c443524d92de0388efea01b6867ca2bedcca422bccc116103026a45\""

  43m   11s     190     kubelet, 192.168.122.186                Warning FailedSync      Error syncing pod, skipping: failed to "CreatePodSandbox" for "awesomeredis-1-bjr6t_default(774fcd7a-319c-11e7-8092-52540073f55c)" with CreatePodSandboxError: "CreatePodSandbox for pod \"awesomeredis-1-bjr6t_default(774fcd7a-319c-11e7-8092-52540073f55c)\" failed: rpc error: code = 2 desc = conflict, name \"default-awesomeredis-1-bjr6t-0\" already reserved for pod \"b15c4042a6cfd542ee45e945d299026f2b303de78773227d06f59217010bb61a\""

```

should we append a random string at the end of the name for pods and containers so we don't fail that way? @sameo @mrunalp do you know what's the expected behavior? with docker?

### PR DESCRIPTION
**Pull request by runcom**
Replaces #499 

Fix #497

### CODE REVIEW

**Comment by runcom** [comment]
@sameo this is still different than what you proposed here https://github.com/kubernetes-incubator/cri-o/issues/497#issuecomment-300473617 - I'm going to try your suggestion and make a PR if necessary (just gathering info on kube behavior when underlying containers are not present on the machine)

File: oci/oci.go [hunk 1]
```diff
@@ -474,7 +474,10 @@ func (r *Runtime) StopContainer(c *Container) error {
 func (r *Runtime) DeleteContainer(c *Container) error {
 	c.opLock.Lock()
 	defer c.opLock.Unlock()
-	return utils.ExecCmdWithStdStreams(os.Stdin, os.Stdout, os.Stderr, r.Path(c), "delete", c.name)
+	if _, err := utils.ExecCmd(r.Path(c), "delete", c.name); err != nil && !strings.Contains(err.Error(), "does not exist") {
```
Comment (sameo) [inline oci/oci.go]: This is `runc` specific, and also specific to the current `runc` implementation. Could we have a more generic implementation where we ping the container process when getting an error ? If the container process is not there, then we ignore the error and return nil ?

File: server/container_remove.go [hunk 2]
```diff
@@ -22,11 +21,8 @@ func (s *Server) RemoveContainer(ctx context.Context, req *pb.RemoveContainerReq
 		return nil, fmt.Errorf("failed to update container state: %v", err)
 	}
 
-	cState := s.runtime.ContainerStatus(c)
-	if cState.Status == oci.ContainerStateCreated || cState.Status == oci.ContainerStateRunning {
-		if err := s.runtime.StopContainer(c); err != nil {
-			return nil, fmt.Errorf("failed to stop container %s: %v", c.ID(), err)
-		}
+	if err := s.runtime.StopContainer(c); err != nil {
```
Comment (sameo) [inline server/container_remove.go]: Could we add a comment or a more verbose commit log, to understand why we're now stopping a container regardless of its state ?

File: server/sandbox_remove.go [hunk 3]
```diff
@@ -36,7 +36,7 @@ func (s *Server) RemovePodSandbox(ctx context.Context, req *pb.RemovePodSandboxR
 		}
 
 		if err := s.runtime.StopContainer(c); err != nil {
-			return fmt.Errorf("failed to stop container %s: %v", c.Name(), err)
+			return nil, fmt.Errorf("failed to stop container %s: %v", c.Name(), err)
```
Comment (sameo) [inline server/sandbox_remove.go]: Is that one part of another commit ?

File: server/container_status.go [hunk 4]
```diff
@@ -18,9 +18,8 @@ func (s *Server) ContainerStatus(ctx context.Context, req *pb.ContainerStatusReq
 		return nil, err
 	}
 
-	if err = s.runtime.UpdateStatus(c); err != nil {
-		return nil, err
-	}
+	// best effort if container is still in runc store...
+	s.runtime.UpdateStatus(c)
```
Comment (sameo) [inline server/container_status.go]: A suggestion here: Could we have `UpdateStatus` return a named error when its `exec.Cmd()` fails, and then ignore that specific error in the 2 cases in this patch ? Otherwise we're ignoring all the other `UpdateStatus()` error paths here.

File: oci/oci.go [hunk 5]
```diff
@@ -486,6 +486,9 @@ func (r *Runtime) UpdateStatus(c *Container) error {
 	defer c.opLock.Unlock()
 	out, err := exec.Command(r.Path(c), "state", c.name).CombinedOutput()
 	if err != nil {
+		if strings.Contains(string(out), "does not exist") {
```
Comment (sameo) [inline oci/oci.go]: Same here: This is `runc` specific and I think we don't want that.
Same remark as before: Could we just ping the process when `exec.Command()` fails and then return an ocid, named error that we can treat specifically ?

File: server/sandbox_status.go [hunk 6]
```diff
@@ -32,6 +33,7 @@ func (s *Server) PodSandboxStatus(ctx context.Context, req *pb.PodSandboxStatusR
 	}
 
 	rStatus := pb.PodSandboxState_SANDBOX_NOTREADY
+
```
Comment (sameo) [inline server/sandbox_status.go]: nitpick: new line added.

File: oci/oci.go (hunk 5 above)
Comment (runcom) [inline oci/oci.go]: Instead of pinging the process (we may have not a PID at all at this point, after a reboot for instance), can't we just say:
"if `runc state` fails for whatever reason, then set the container as stopped as below and return `nil`". @sameo how does that sound?

File: server/sandbox_remove.go (hunk 3 above)
Comment (runcom) [inline server/sandbox_remove.go]: yup, sorry, I ended up committing w/o this fix

File: oci/oci.go (hunk 5 above)
Comment (runcom) [inline oci/oci.go]: actually, you already said what I've proposed here https://github.com/kubernetes-incubator/cri-o/pull/505#discussion_r115986596 so yeah, will fix this.

File: server/container_remove.go (hunk 2 above)
Comment (mrunalp) [inline server/container_remove.go]: I think it may be better to retain state check outside rather than move it into StopContainer.

File: server/sandbox_list.go [hunk 7]
```diff
@@ -59,9 +59,8 @@ func (s *Server) ListPodSandbox(ctx context.Context, req *pb.ListPodSandboxReque
 			// it's better not to panic
 			continue
 		}
-		if err := s.runtime.UpdateStatus(podInfraContainer); err != nil {
-			return nil, err
-		}
+		s.runtime.UpdateStatus(podInfraContainer)
```
Comment (mrunalp) [inline server/sandbox_list.go]: I think @sameo previous comment applies here as well.

File: server/sandbox_remove.go [hunk 8]
```diff
@@ -36,12 +35,8 @@ func (s *Server) RemovePodSandbox(ctx context.Context, req *pb.RemovePodSandboxR
 			return nil, fmt.Errorf("failed to update container state: %v", err)
 		}
 
-		cState := s.runtime.ContainerStatus(c)
-		if cState.Status == oci.ContainerStateCreated || cState.Status == oci.ContainerStateRunning {
-			if err := s.runtime.StopContainer(c); err != nil {
-				// Assume container is already stopped
-				logrus.Warnf("failed to stop container %s: %v", c.Name(), err)
-			}
+		if err := s.runtime.StopContainer(c); err != nil {
```
Comment (mrunalp) [inline server/sandbox_remove.go]: Same as above.

**Comment by runcom** [comment]
alright, reworked again and tested, seems to be working fine if rebooting with #513

**Comment by runcom** [comment]
rebased, going to test this out one last time with openshift and should be good to go, meanwhile, @mrunalp @sameo PTAL

**Comment by runcom** [comment]
meanwhile I'll also add some tests

File: oci/oci.go (hunk 1 above)
Comment (runcom) [inline oci/oci.go]: on delete we won't have a container pid cause it's already stopped and no pid is assigned to the continer...

Comment (runcom) [inline oci/oci.go]: I don't actually have a good solution for delete - @mrunalp @sameo do you have other in mind which will work for delete in the case delete throws a `does not exist`?

**Comment by runcom** [comment]
retest

**Comment by runcom** [comment]
retest

**Comment by runcom** [comment]
retest

**Comment by runcom** [comment]
retest

**Comment by runcom** [comment]
retest

**Comment by runcom** [comment]
retest

File: oci/oci.go (hunk 1 above)
Comment (mrunalp) [inline oci/oci.go]: We should probably have a delete --force not fail on container not existing in runc.

Comment (runcom) [inline oci/oci.go]: @mrunalp the thing it should always be forced then...

**Comment by runcom** [comment]
retest

**Comment by runcom** [comment]
retest

File: oci/oci.go (hunk 1 above)
Comment (runcom) [inline oci/oci.go]: https://github.com/opencontainers/runc/pull/1451 has been merged, let's use `-f` so we ignore not exist error while still bubbling up other errors, I'll fix it.

Comment (runcom) [inline oci/oci.go]: fixed

**Comment by runcom** [comment]
all, this is good to go now, I'll run another test for kube/origin just to make sure

File: server/sandbox_remove.go [hunk 9]
```diff
@@ -107,16 +107,15 @@ func (s *Server) RemovePodSandbox(ctx context.Context, req *pb.RemovePodSandboxR
 	return resp, nil
 }
 
-// RemoveAllPodSandboxes removes all pod sandboxes
-func (s *Server) RemoveAllPodSandboxes() {
-	logrus.Debugf("RemoveAllPodSandboxes")
-	s.Update()
+// StopAllPodSandboxes removes all pod sandboxes
```
Comment (sameo) [inline server/sandbox_remove.go]: Nitpick: StopAllPodSandboxes **stops** all pod sandboxes

**Comment by sameo** [comment]
Only one nitpick, it can be fixed through a further PR. No need to respin/rebase/retest.
LGTM

**Comment by runcom** [comment]
awesome, @mrunalp up to you now :)

File: server/sandbox_stop.go [hunk 10]
```diff
@@ -52,9 +52,23 @@ func (s *Server) StopPodSandbox(ctx context.Context, req *pb.StopPodSandboxReque
...
 		}
+		s.containerStateToDisk(c)
 	}
 
 	resp := &pb.StopPodSandboxResponse{}
 	logrus.Debugf("StopPodSandboxResponse: %+v", resp)
 	return resp, nil
 }
+
+// StopAllPodSandboxes removes all pod sandboxes
```
Comment (mrunalp) [inline server/sandbox_stop.go]: nit: stops. can do it as part of another PR later.

**Comment by mrunalp** [comment]
LGTM
