### PR TITLE
server: containers restore

### LINKED ISSUE #111: cannot start a created container using the ID
Maybe I'm misunderstanding how the interface is meant to work, because I'm expecting it to kinda work like Docker/runC:

```
 % sudo ./ocic pod create --name sandbox0 --config test/testdata/sandbox_config.json
fe6a1bce4f27392b38f7c9066112a82ec39e4220e7ac6635873113168a725e2c
% sudo ./ocic container create --pod fe6a1bce4f27392b38f7c9066112a82ec39e4220e7ac6635873113168a725e2c --config test/testdata/container_config.json
aecc2d844d19f127c0a026e2325a6357e0a59a7c4b60130e63d4e4eab9ab3b0c
% sudo ./ocic container list
ID: default-sandbox0-0-container1-0
Pod: fe6a1bce4f27392b38f7c9066112a82ec39e4220e7ac6635873113168a725e2c
Status: CREATED
Created: 2016-10-07 15:01:02 +1100 AEDT
ID: default-sandbox0-0-infra
Pod: fe6a1bce4f27392b38f7c9066112a82ec39e4220e7ac6635873113168a725e2c
Status: RUNNING
Created: 2016-10-07 15:00:17 +1100 AEDT
% sudo ./ocic container start --id default-sandbox0-0-container1-0
FATA[0000] Starting the container failed: rpc error: code = 2 desc = container with ID starting with default-sandbox0-0-container1-0 not found: ID does not exist
```

Am I using the wrong ID or something? Or is this an actual bug?

### PR DESCRIPTION
**Pull request by runcom**
Close https://github.com/kubernetes-incubator/cri-o/issues/17
Close #111

Keep in mind this comment https://github.com/kubernetes-incubator/cri-o/issues/17#issuecomment-252249629 meaning we don't have any way right now to fully restore if someone plays with runc directly (we'll address that ofc).

@rhatdan this is also fixing https://github.com/kubernetes-incubator/cri-o/issues/102#issuecomment-252259251 by storing the process label in the sandbox's config.json.

@mrunalp PTAL - I'm writing some tests but won't likely finish soon (this weekend at least), I'll open another PR shortly.

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

File: server/sandbox.go [hunk 1]
```diff
@@ -172,6 +172,7 @@ func (s *Server) RunPodSandbox(ctx context.Context, req *pb.RunPodSandboxRequest
 		if err != nil {
 			return nil, err
 		}
+		g.SetProcessSelinuxLabel(processLabel)
 	}
```
Comment (rhatdan) [inline server/sandbox.go]: Do we also need to save the FileLabel, or do you want to regenerate that when we load into the config.json on ocid restart?

Comment (rhatdan) [inline server/sandbox.go]: specgen.SetLinuxMountLabel(mountLabel)

Comment (runcom) [inline server/sandbox.go]: @rhatdan we regenerate that when we load the container's sandbox mountLabel from the processLabel so need to save that

Comment (rhatdan) [inline server/sandbox.go]: Great

Comment (runcom) [inline server/sandbox.go]: @rhatdan do we need `label.ReserveLabel` here right? is there any way to release the label though? like on container's delete

Comment (rhatdan) [inline server/sandbox.go]: I am not sure we need it here.  But we need to Reserve the label when OCID reads the existing containers.

Yes, I forgot about that one.  We need to release it also.
label.UnreserveLabel(processLabel)

On Delete

**Comment by runcom** [comment]
> But we need to Reserve the label when OCID reads the existing containers.

alright, so we need that at container restore and on create

File: server/sandbox.go (hunk 1 above)
Comment (rhatdan) [inline server/sandbox.go]: OCID carries a list of MCS Labels that are currently in use in memory.  When it creates a new container with InitLabel() It looks for an unused MCS label and reserves it.  
If you stop OCID and restart it, it needs to figure out ALL of the containers that are created (Whether they are running or not) and repopulate the table of Used MCS Labels.  

InitLabels automatically updates the Table.

We need ReserveLabel any time OCID starts for each container image, and we need UnreserveLabel any time a container is Deleted.

Comment (runcom) [inline server/sandbox.go]: ack, now I get it thx

Comment (runcom) [inline server/sandbox.go]: @rhatdan updated PTAL

File: server/sandbox.go [hunk 2]
```diff
@@ -353,6 +354,13 @@ func (s *Server) RemovePodSandbox(ctx context.Context, req *pb.RemovePodSandboxR
 		s.removeContainer(c)
 	}
 
+	if err := label.UnreserveLabel(sb.processLabel); err != nil {
+		return nil, err
+	}
+	if err := label.UnreserveLabel(sb.mountLabel); err != nil {
```
Comment (rhatdan) [inline server/sandbox.go]: Only need the call for the processlabel.  SELinux is just grabbing the MCS portion and removing it, Calling this for mountlabel would have no effect.

File: server/server.go [hunk 3]
```diff
@@ -72,31 +115,60 @@ func (s *Server) loadSandbox(id string) error {
 	})
 	sandboxPath := filepath.Join(s.sandboxDir, id)
 
-	scontainer, err := oci.NewContainer(m.Annotations["ocid/container_id"], m.Annotations["ocid/container_name"], sandboxPath, sandboxPath, labels, id, false)
+	if err := label.ReserveLabel(processLabel); err != nil {
+		return err
+	}
+	if err := label.ReserveLabel(mountLabel); err != nil {
```
Comment (rhatdan) [inline server/server.go]: Same as above, Only Reserve the Processlabel.

File: server/server.go [hunk 4]
```diff
@@ -72,31 +115,60 @@ func (s *Server) loadSandbox(id string) error {
...
 	return nil
 }
 
-func (s *Server) restore() error {
-	dir, err := ioutil.ReadDir(s.sandboxDir)
+func (s *Server) restore() {
+	sandboxDir, err := ioutil.ReadDir(s.sandboxDir)
 	if err != nil {
-		return err
+		logrus.Warnf("could not read sandbox directory %s: %v", sandboxDir, err)
```
Comment (rhatdan) [inline server/server.go]: Should this be fatal?

Comment (runcom) [inline server/server.go]: should it? if we fail to load a pod/container should we entirely bail out? docker is just skipping that container's load, shall we fail instead?

File: server/sandbox.go (hunk 2 above)
Comment (runcom) [inline server/sandbox.go]: fixed

File: server/server.go (hunk 3 above)
Comment (runcom) [inline server/server.go]: fixed

**Comment by runcom** [comment]
@mrunalp @rhatdan PTAL I believe I took care of every comment so far

**Comment by mrunalp** [comment]
@runcom Worth adding a test? Start a pod and container, restart ocid and then list pod and containers again to see if they are visible.

**Comment by runcom** [comment]
@mrunalp adding one, but `cleanup_pods` is broken because `pod list` returns multi lines output, we need a way to run the tests in Travis or better Jankins :(

File: server/server.go (hunk 4 above)
Comment (rhatdan) [inline server/server.go]: I was looking at this specific case where you were failing to read the entire directory.  Not each container image.

**Comment by runcom** [comment]
DO NOT MERGE: fixing the tests

**Comment by mrunalp** [comment]
@runcom Does the $output variable only capture one line?

**Comment by runcom** [comment]
@mrunalp it doesn't, cleanup_pods wrongly read every line and tries to wrongly stop pods with wrong ids. I'll fix that later today (afk right now).

**Comment by runcom** [comment]
@mrunalp PTAL (added a test and a bunch of fixes)

**Comment by mrunalp** [comment]
Looks good. Will run it locally before merging.

**Comment by mrunalp** [comment]
LGTM
