### PR TITLE
server: check netns path on pod stop

### LINKED ISSUE #232: StopPodSandbox() fails when called multiple times and network enabled
According to the CRI specs:

```
This call is idempotent, and must not return an error if all relevant
resources have already been reclaimed. kubelet will call StopPodSandbox
at least once before calling RemovePodSandbox. It will also attempt to
reclaim resources eagerly, as soon as a sandbox is not needed. Hence,
multiple StopPodSandbox calls are expected.
```

However when running CRI-O `StopPodSandbox()` more than once on the same pod, ocicni returns an error:

```
E1206 11:16:58.643915   29033 ocicni.go:233] Error deleting network: failed to Statfs "/proc/29117/ns/net": no such file or directory
```

### PR DESCRIPTION
**Pull request by runcom**
Fix #232 

(tested locally with @sameo's config https://github.com/kubernetes-incubator/cri-o/issues/232#issuecomment-265130836 and cni plugins under `/opt/cni/bin/`)

@mrunalp PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@sameo in order for this PR to work you need to also use #235

File: server/sandbox_stop.go [hunk 1]
```diff
@@ -24,10 +25,13 @@ func (s *Server) StopPodSandbox(ctx context.Context, req *pb.StopPodSandboxReque
 	if err != nil {
 		return nil, err
 	}
-
-	if err := s.netPlugin.TearDownPod(netnsPath, podNamespace, sb.id, podInfraContainer.Name()); err != nil {
-		return nil, fmt.Errorf("failed to destroy network for container %s in sandbox %s: %v",
-			podInfraContainer.Name(), sb.id, err)
+	if _, err := os.Stat(netnsPath); err == nil {
```
Comment (rhatdan) [inline server/sandbox_stop.go]: Why not check for the error first and report it back, then call teardown, if netnsPath exists.

Comment (runcom) [inline server/sandbox_stop.go]: you need an additional check for the teardown then...

```
if err :=stat(netnsPath) - err != nil && !os.IsNotExists(err) {
return err
}
if err == nil { // because it can be os.NotExist
  teardown
}
```

Comment (rhatdan) [inline server/sandbox_stop.go]:
```
if err :=stat(netnsPath) - err != nil {
   if os.IsNotExists(err) {
        teardown()
  } else {
          return err
  }
}
```

Comment (runcom) [inline server/sandbox_stop.go]: We call teardown only on err == nil - other error are either reported or skipped (like not exists). Your example only call teardown if there's any error with Stat

Comment (rhatdan) [inline server/sandbox_stop.go]: Oops sorry you are right.

Comment (rhatdan) [inline server/sandbox_stop.go]:
```
if err :=stat(netnsPath) - err != nil {
   if os.IsNotExists(err) {
        return nil
  } else {
          return err
  }
}
```

Comment (runcom) [inline server/sandbox_stop.go]: mmm :confused: 

the thing is:

1. stat netns
2. if there's no error in stat'ing, call teardown
3. if there's any error in stat'ing other than "not found" error, report it
4. otherwise skip the whole thing

your code does:

1. if there's an error in stat'ing
2. if the error is "not found", exit the stop container routine (???)
3. otherwise return the error

**Comment by sameo** [comment]
@runcom This fixes #232

File: server/sandbox_stop.go (hunk 1 above)
Comment (rhatdan) [inline server/sandbox_stop.go]: I am suggesting that you add my code to check for netnspath, if it exists you continue to the original code and teardown.

Comment (rhatdan) [inline server/sandbox_stop.go]: Updated my example above.

Comment (runcom) [inline server/sandbox_stop.go]: @rhatdan your code is exiting the stop routine w/o cleaning the containers below the teardown (we should just skip the teardown, not entirely exit the stop request when netns path doesn't exit (or there's an error stat'ing)

Comment (rhatdan) [inline server/sandbox_stop.go]: Ok,  Should we just ignore the error on netns, if it is not notexists?

Comment (runcom) [inline server/sandbox_stop.go]: yes, that's what my code does as well. If no error on stat then teardown, if error other that not exists, return, otherwise continue the stop routine to cleanup other resources.

Comment (sameo) [inline server/sandbox_stop.go]: @rhatdan If the netns does not exist, we should not attempt to tear it down or else Stop() will fail, and that does not comply with the CRI expectations.

Comment (rhatdan) [inline server/sandbox_stop.go]: Ok, LGTM

Comment (rhatdan) [inline server/sandbox_stop.go]: @sameo I was just wondering if not able to stat the file should be an error situation blocking the the rest of the Stop.

Comment (rhatdan) [inline server/sandbox_stop.go]: Maybe we should return 
fmt.Errorf("Unable to stat %s: %v", netnsPath, err)

Comment (runcom) [inline server/sandbox_stop.go]: > fmt.Errorf("Unable to stat %s: %v", netnsPath, err)

Golang should already tell us that - but I've added more context to the error anyway

**Comment by sameo** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM
